language: python

python:
  - "3.8"

# command to install dependencies
install:
  - pip install tox

# command to run tests
script: 
  - pytest

matrix:
  include:
    - python: 3.8
      env: TOXENV=docstyle
      dist: xenial
      sudo: true